version: "3.9"
services:
  server:
    container_name: server
    restart: always
    build:
      context: ./server
    ports:
      - "${SERVER_PORT:-4000}:4000"
    environment:
      # need to match with .env variables. Docker will replace
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      # host path in docker
      DB_HOST: database
      DB_DATABASE: "${DB_DATABASE}"

  client:
    container_name: client
    restart: always
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT:-80}:80"

  database:
    image: mysql:8
    restart: always
    # Docker image environment variables https://hub.docker.com/_/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: